default: &default
  adapter: postgresql
  user: swish
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: volunteer_dev

test:
  <<: *default
  database: volunteer_test

production:
  <<: *default
  database: volunteer
  username: root
  password: root
  host: 127.0.0.1
  port: 3306  
